Name: AdaptiveScheduledTasks
Description: Collect binaries mentioned in the ScheduledTasks
Targets:
- Name: Commands
  Comment: Includes results of Windows.System.TaskScheduler
  VQL: |
    SELECT * FROM foreach(row={
      SELECT _value AS Row
      FROM items(item={
         SELECT * FROM Artifact.Windows.System.TaskScheduler()
      })
      WHERE Row.Command
    }, query={
      SELECT * FROM TryToDownload(OSPath=Row.Command, Row=Row)
    })
