Name: _Live
Description: Collect live artifacts
Targets:
 - Name: ProcessListing
   Ref: PsList

 - Name: AdaptiveScheduledTasks
   Ref: AdaptiveScheduledTasks

 - Name: PrefetchBinaries
   Ref: PrefetchBinaries

 - Name: LnkTargets
   Ref: LnkTargets
