Name: PsList
Description: Collect all currently running binaries.
Targets:
- Name: From Pslist
  Comment: Uses PSList to get all running binaries.
  VQL: |
    SELECT * FROM foreach(workers=WORKERS, row={
      SELECT _value AS Row
      FROM items(item={
        SELECT * FROM pslist()
      })
    }, query={
       SELECT * FROM TryToDownload(OSPath=Row.Exe, Row=Row)
    })
