name: Test generated artifacts

on: [pull_request]

jobs:
  build:
    name: Triage Rules Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.23'
      id: go

    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download Latest Velociraptor
      uses: robinraju/release-downloader@v1
      id: velociraptor
      with:
        repository: velocidex/velociraptor
        tag: v0.74
        fileName: "velociraptor-v0.74.5-linux-amd64-musl"
        out-file-path: tests

    - name: Run tests
      run: |
        make test

    - name: Build Artifacts
      run: |
        make compile

    - name: Run Velociraptor
      run: |
        mv ${{ fromJson(steps.velociraptor.outputs.downloaded_files)[0]}} ./tests/velociraptor
        chmod +x ./tests/velociraptor
        ls -l ./output/
        ./tests/velociraptor artifacts verify --builtin -v ./output/*.yaml

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifact
        path: tests/testcases

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output
        path: output
